version: "3.8"

name: finance-manager-project

services:
  app:
    image: finance-manager-image
    container_name: finance-manager-container
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
