# Generated by Django 5.0.6 on 2024-06-05 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('main_category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sub_category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('correction', 'correction'), ('approve', 'approve'), ('reject', 'reject')], db_index=True, default='pending', max_length=255, null=True)),
                ('payment', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_time_stamp', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_time_stamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('account_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_time_stamp'],
            },
        ),
    ]
