# Generated by Django 5.0.6 on 2024-07-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-updated_time_stamp']},
        ),
        migrations.AddField(
            model_name='report',
            name='report_note',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
