# Generated by Django 5.0.6 on 2024-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_report_report_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='payment',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
